# Generated by Django 5.2.3 on 2025-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('business_keys', models.CharField(help_text='Campos que formam a chave de negócio, separados por vírgula.', max_length=500)),
            ],
        ),
    ]
