# Generated by Django 5.2.3 on 2025-06-23 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_key', models.CharField(default='id', max_length=100)),
                ('load_date', models.CharField(default='load_date', max_length=100)),
                ('record_source', models.CharField(default='record_source', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('load_date', models.CharField(default='load_date', max_length=100)),
                ('record_source', models.CharField(default='record_source', max_length=100)),
                ('hubs', models.ManyToManyField(to='modeler.hub')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='modeler.project')),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='modeler.project'),
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attributes', models.JSONField(default=dict)),
                ('load_date', models.CharField(default='load_date', max_length=100)),
                ('record_source', models.CharField(default='record_source', max_length=100)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeler.hub')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeler.link')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='modeler.project')),
            ],
        ),
    ]
