# Generated by Django 5.2.3 on 2025-06-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modeler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='link',
        ),
        migrations.AddField(
            model_name='satellite',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='business_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hub',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.project'),
        ),
        migrations.AlterField(
            model_name='link',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.project'),
        ),
    ]
