# Generated by Django 5.2.3 on 2025-06-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeler', '0003_alter_satellite_content_type_alter_satellite_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='modeler.project'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hubs',
            field=models.ManyToManyField(related_name='links', to='modeler.hub'),
        ),
        migrations.AlterField(
            model_name='link',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='modeler.project'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='modeler.project'),
        ),
    ]
