# Generated by Django 5.2.3 on 2025-06-23 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeler', '0003_satellite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='load_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hub',
            name='record_source',
            field=models.CharField(default='DefaultSource', max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='load_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='link',
            name='record_source',
            field=models.CharField(default='DefaultSource', max_length=255),
        ),
        migrations.AddField(
            model_name='satellite',
            name='load_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='satellite',
            name='record_source',
            field=models.CharField(default='DefaultSource', max_length=255),
        ),
    ]
