# Generated by Django 5.2.3 on 2025-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeler', '0004_hub_load_date_hub_record_source_link_load_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
